/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'
import { Route as LobbyCodeRevealRouteImport } from './routes/lobby.$code.reveal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRevealRoute = LobbyCodeRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => LobbyCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby/$code': typeof LobbyCodeRouteWithChildren
  '/lobby/$code/reveal': typeof LobbyCodeRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby/$code': typeof LobbyCodeRouteWithChildren
  '/lobby/$code/reveal': typeof LobbyCodeRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lobby/$code': typeof LobbyCodeRouteWithChildren
  '/lobby/$code/reveal': typeof LobbyCodeRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lobby/$code' | '/lobby/$code/reveal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lobby/$code' | '/lobby/$code/reveal'
  id: '__root__' | '/' | '/lobby/$code' | '/lobby/$code/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyCodeRoute: typeof LobbyCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code/reveal': {
      id: '/lobby/$code/reveal'
      path: '/reveal'
      fullPath: '/lobby/$code/reveal'
      preLoaderRoute: typeof LobbyCodeRevealRouteImport
      parentRoute: typeof LobbyCodeRoute
    }
  }
}

interface LobbyCodeRouteChildren {
  LobbyCodeRevealRoute: typeof LobbyCodeRevealRoute
}

const LobbyCodeRouteChildren: LobbyCodeRouteChildren = {
  LobbyCodeRevealRoute: LobbyCodeRevealRoute,
}

const LobbyCodeRouteWithChildren = LobbyCodeRoute._addFileChildren(
  LobbyCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyCodeRoute: LobbyCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
